platform:
  - x64
environment:
  global:
    MSYS2_BASEVER: 20150512
  matrix:
    - MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
#    - MSYS2_ARCH: i686
#      MSYSTEM: MINGW32
#      MSYS2_BITS: 32
install:
  - appveyor DownloadFile "http://kent.dl.sourceforge.net/project/msys2/Base/%MSYS2_ARCH%/msys2-base-%MSYS2_ARCH%-%MSYS2_BASEVER%.tar.xz" -FileName "msys2.tar.xz"
  - 7z x msys2.tar.xz
  - 7z x msys2.tar > NUL
  - msys%MSYS2_BITS%\usr\bin\bash -lc ""
  - msys%MSYS2_BITS%\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -Suy mingw-w64-%MSYS2_ARCH%-gettext && break || sleep 15; done" # for libintl
  - msys%MSYS2_BITS%\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -Suy mingw-w64-%MSYS2_ARCH%-{ragel,icu,gobject-introspection} libtool pkg-config gcc make autoconf automake perl python && break || sleep 15; done"
  - msys%MSYS2_BITS%\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -Suy glib2 glib2-devel && break || sleep 15; done" # for font functions / tests / utils
  - msys%MSYS2_BITS%\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -Suy mingw-w64-%MSYS2_ARCH%-glib2 && break || sleep 15; done" # //
  - msys%MSYS2_BITS%\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -Suy mingw-w64-%MSYS2_ARCH%-cairo && break || sleep 15; done" # for utils
  - msys%MSYS2_BITS%\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -Suy mingw-w64-%MSYS2_ARCH%-freetype && break || sleep 15; done" # for font functions
  - msys%MSYS2_BITS%\usr\bin\dash -lc "exec 0</dev/null; /usr/bin/rebaseall -vp"
build_script:
  - msys%MSYS2_BITS%\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; ./autogen.sh --with-uniscribe --with-freetype --with-glib --with-gobject --with-cairo --with-icu; LD_LIBRARY_PATH=/usr/lib/w32api:$LD_LIBRARY_PATH make check"
# disable automatic tests
test: off
